// <auto-generated />
using System;
using Earn_Learn.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EarnLearn.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260524180804_DodajPredmetiNaCekanjuJson")]
    partial class DodajPredmetiNaCekanjuJson
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Earn_Learn.Models.Korisnik", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<int?>("BrojIndeksa")
                        .HasColumnType("int");

                    b.Property<int?>("BrojOdrzanihCasova")
                        .HasColumnType("int");

                    b.Property<double?>("CijenaPoSatu")
                        .HasColumnType("double");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DatumRegistracije")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("GodinaStudija")
                        .HasColumnType("int");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("PredmetNaCekanjaId")
                        .HasColumnType("int");

                    b.Property<string>("PredmetiNaCekanjuJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PrilogOcjene")
                        .HasColumnType("longtext");

                    b.Property<double?>("ProsjecnaOcjena")
                        .HasColumnType("double");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<double>("StanjeRacuna")
                        .HasColumnType("double");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Uloga")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool?>("VerifikovanTutor")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Earn_Learn.Models.KorisnikPredmet", b =>
                {
                    b.Property<string>("idKorisnika")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("idPredmeta")
                        .HasColumnType("int");

                    b.HasKey("idKorisnika", "idPredmeta");

                    b.ToTable("KorisnikPredmet");
                });

            modelBuilder.Entity("Earn_Learn.Models.Obavjestenje", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("datumSlanja")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("idKorisnika")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("naslov")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("procitano")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("sadrzaj")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("Obavjestenje");
                });

            modelBuilder.Entity("Earn_Learn.Models.Predmet", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("naziv")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("Predmet");

                    b.HasData(
                        new
                        {
                            id = 1,
                            naziv = "Administracija računarskih mreža"
                        },
                        new
                        {
                            id = 2,
                            naziv = "Aktuatori"
                        },
                        new
                        {
                            id = 3,
                            naziv = "Algoritmi i strukture podataka"
                        },
                        new
                        {
                            id = 4,
                            naziv = "Analiza signala i sistema"
                        },
                        new
                        {
                            id = 5,
                            naziv = "Analogna elektronika"
                        },
                        new
                        {
                            id = 6,
                            naziv = "Antene i prostiranje talasa"
                        },
                        new
                        {
                            id = 7,
                            naziv = "Automati i formalni jezici"
                        },
                        new
                        {
                            id = 8,
                            naziv = "CAD-CAM inžinjering"
                        },
                        new
                        {
                            id = 9,
                            naziv = "Digitalna elektronika"
                        },
                        new
                        {
                            id = 10,
                            naziv = "Digitalni integrirani krugovi"
                        },
                        new
                        {
                            id = 11,
                            naziv = "Digitalni sistemi upravljanja"
                        },
                        new
                        {
                            id = 12,
                            naziv = "Digitalno procesiranje signala"
                        },
                        new
                        {
                            id = 13,
                            naziv = "Dinamika fluida i toplotnih sistema"
                        },
                        new
                        {
                            id = 14,
                            naziv = "Dinamički sistemi"
                        },
                        new
                        {
                            id = 15,
                            naziv = "Diskretna matematika"
                        },
                        new
                        {
                            id = 16,
                            naziv = "Dizajn i arhitektura softverskih sistema"
                        },
                        new
                        {
                            id = 17,
                            naziv = "Električna mjerenja"
                        },
                        new
                        {
                            id = 18,
                            naziv = "Električna postrojenja"
                        },
                        new
                        {
                            id = 19,
                            naziv = "Električne instalacije i mjere sigurnosti"
                        },
                        new
                        {
                            id = 20,
                            naziv = "Električne mašine"
                        },
                        new
                        {
                            id = 21,
                            naziv = "Električni krugovi I"
                        },
                        new
                        {
                            id = 22,
                            naziv = "Električni krugovi 2"
                        },
                        new
                        {
                            id = 23,
                            naziv = "Električni sistemi u transportu"
                        },
                        new
                        {
                            id = 24,
                            naziv = "Elektroenergetski sistemi"
                        },
                        new
                        {
                            id = 25,
                            naziv = "Elektromotorni pogoni"
                        },
                        new
                        {
                            id = 26,
                            naziv = "Elektronika TK 1"
                        },
                        new
                        {
                            id = 27,
                            naziv = "Elektronika TK 2"
                        },
                        new
                        {
                            id = 28,
                            naziv = "Elektronički elementi i sklopovi"
                        },
                        new
                        {
                            id = 29,
                            naziv = "Elektrotehnički materijali"
                        },
                        new
                        {
                            id = 30,
                            naziv = "Elektrotermička konverzija energije"
                        },
                        new
                        {
                            id = 31,
                            naziv = "Energetska elektronika"
                        },
                        new
                        {
                            id = 32,
                            naziv = "Inženjerska ekonomika"
                        },
                        new
                        {
                            id = 33,
                            naziv = "Inženjerska elektromagnetika"
                        },
                        new
                        {
                            id = 34,
                            naziv = "Inženjerska fizika I"
                        },
                        new
                        {
                            id = 35,
                            naziv = "Inženjerska fizika II"
                        },
                        new
                        {
                            id = 36,
                            naziv = "Inžinjerska matematika I"
                        },
                        new
                        {
                            id = 37,
                            naziv = "Inžinjerska matematika II"
                        },
                        new
                        {
                            id = 38,
                            naziv = "Inžinjerska matematika 3"
                        },
                        new
                        {
                            id = 39,
                            naziv = "Kanalno kodiranje"
                        },
                        new
                        {
                            id = 40,
                            naziv = "Komponente i tehnologije"
                        },
                        new
                        {
                            id = 41,
                            naziv = "Komunikacijski protokoli i mreže"
                        },
                        new
                        {
                            id = 42,
                            naziv = "Komutacioni sistemi"
                        },
                        new
                        {
                            id = 43,
                            naziv = "Kvalitet električne energije"
                        },
                        new
                        {
                            id = 44,
                            naziv = "Linearna algebra i geometrija"
                        },
                        new
                        {
                            id = 45,
                            naziv = "Linearni sistemi automatskog upravljanja"
                        },
                        new
                        {
                            id = 46,
                            naziv = "Logički dizajn"
                        },
                        new
                        {
                            id = 47,
                            naziv = "Matematička logika i teorija izračunljivosti"
                        },
                        new
                        {
                            id = 48,
                            naziv = "Mehatronika"
                        },
                        new
                        {
                            id = 49,
                            naziv = "Mikrovalni komunikacijski sistemi"
                        },
                        new
                        {
                            id = 50,
                            naziv = "Mjerenja u telekomunikacijama"
                        },
                        new
                        {
                            id = 51,
                            naziv = "Mobilne komunikacije"
                        },
                        new
                        {
                            id = 52,
                            naziv = "Modeliranje i simulacija"
                        },
                        new
                        {
                            id = 53,
                            naziv = "Nove generacije mreža i usluga"
                        },
                        new
                        {
                            id = 54,
                            naziv = "Numerički algoritmi"
                        },
                        new
                        {
                            id = 55,
                            naziv = "Objektno orijentisana analiza i dizajn"
                        },
                        new
                        {
                            id = 56,
                            naziv = "Održavanje električnih sistema"
                        },
                        new
                        {
                            id = 57,
                            naziv = "Operativni sistemi"
                        },
                        new
                        {
                            id = 58,
                            naziv = "Organizacija i osnove upravljanja mrežom"
                        },
                        new
                        {
                            id = 59,
                            naziv = "Organizacija softverskog projekta"
                        },
                        new
                        {
                            id = 60,
                            naziv = "Osnove baza podataka"
                        },
                        new
                        {
                            id = 61,
                            naziv = "Osnove elektroenergetskih sistema"
                        },
                        new
                        {
                            id = 62,
                            naziv = "Osnove elektrotehnike"
                        },
                        new
                        {
                            id = 63,
                            naziv = "Osnove informacionih sistema"
                        },
                        new
                        {
                            id = 64,
                            naziv = "Osnove mehatronike"
                        },
                        new
                        {
                            id = 65,
                            naziv = "Osnove operacionih istraživanja"
                        },
                        new
                        {
                            id = 66,
                            naziv = "Osnove optoelektronike"
                        },
                        new
                        {
                            id = 67,
                            naziv = "Osnove računarskih mreža"
                        },
                        new
                        {
                            id = 68,
                            naziv = "Osnove računarstva"
                        },
                        new
                        {
                            id = 69,
                            naziv = "Osnove sistema automatskog upravljanja"
                        },
                        new
                        {
                            id = 70,
                            naziv = "Osnove telekomunikacija"
                        },
                        new
                        {
                            id = 71,
                            naziv = "Osnovi signalizacionih protokola"
                        },
                        new
                        {
                            id = 72,
                            naziv = "Poslovni web sistemi"
                        },
                        new
                        {
                            id = 73,
                            naziv = "Pouzdanost električnih elemenata i sistema"
                        },
                        new
                        {
                            id = 74,
                            naziv = "Programski jezici i prevodioci"
                        },
                        new
                        {
                            id = 75,
                            naziv = "Proizvodnja električne energije"
                        },
                        new
                        {
                            id = 76,
                            naziv = "Projektovanje i sinteza digitalnih sistema"
                        },
                        new
                        {
                            id = 77,
                            naziv = "Projektovanje informacionih sistema"
                        },
                        new
                        {
                            id = 78,
                            naziv = "Projektovanje logičkih sistema"
                        },
                        new
                        {
                            id = 79,
                            naziv = "Projektovanje mikroprocersorskih sistema"
                        },
                        new
                        {
                            id = 80,
                            naziv = "Radiotehnika"
                        },
                        new
                        {
                            id = 81,
                            naziv = "Razvoj mobilnih aplikacija"
                        },
                        new
                        {
                            id = 82,
                            naziv = "Razvoj programskih rješenja"
                        },
                        new
                        {
                            id = 83,
                            naziv = "Računarska grafika"
                        },
                        new
                        {
                            id = 84,
                            naziv = "Računarske arhitekture"
                        },
                        new
                        {
                            id = 85,
                            naziv = "Računarsko modeliranje i simulacije"
                        },
                        new
                        {
                            id = 86,
                            naziv = "Robotika 1"
                        },
                        new
                        {
                            id = 87,
                            naziv = "Senzori i pretvarači"
                        },
                        new
                        {
                            id = 88,
                            naziv = "Sistemsko programiranje"
                        },
                        new
                        {
                            id = 89,
                            naziv = "Softverski inženjering"
                        },
                        new
                        {
                            id = 90,
                            naziv = "Statistička teorija signala"
                        },
                        new
                        {
                            id = 91,
                            naziv = "Strukture i režimi rada elektroenergetskih sistema"
                        },
                        new
                        {
                            id = 92,
                            naziv = "Tehnika visokog napona"
                        },
                        new
                        {
                            id = 93,
                            naziv = "Tehnike programiranja"
                        },
                        new
                        {
                            id = 94,
                            naziv = "Tehnologija visokonaponske izolacije"
                        },
                        new
                        {
                            id = 95,
                            naziv = "Tehnologije televizije"
                        },
                        new
                        {
                            id = 96,
                            naziv = "Telekomunikacione tehnike 1"
                        },
                        new
                        {
                            id = 97,
                            naziv = "Telekomunikacione tehnike II"
                        },
                        new
                        {
                            id = 98,
                            naziv = "Teorija elektromagnetnih polja"
                        },
                        new
                        {
                            id = 99,
                            naziv = "Teorija informacija i izvorno kodiranje"
                        },
                        new
                        {
                            id = 100,
                            naziv = "Teorija prometa"
                        },
                        new
                        {
                            id = 101,
                            naziv = "Teorija signala"
                        },
                        new
                        {
                            id = 102,
                            naziv = "Ugradbeni sistemi"
                        },
                        new
                        {
                            id = 103,
                            naziv = "Upravljanje potrošnjom električne energije"
                        },
                        new
                        {
                            id = 104,
                            naziv = "Verifikacija i validacija softvera"
                        },
                        new
                        {
                            id = 105,
                            naziv = "Vjerovatnoća i statistika"
                        },
                        new
                        {
                            id = 106,
                            naziv = "Vještačka inteligencija"
                        },
                        new
                        {
                            id = 107,
                            naziv = "Web tehnologije"
                        });
                });

            modelBuilder.Entity("Earn_Learn.Models.Prijava", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DatumPrijave")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("IdPrijavitelja")
                        .HasColumnType("longtext");

                    b.Property<string>("Naslov")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PrijavljeniTutorId")
                        .HasColumnType("longtext");

                    b.Property<int?>("RecenzijaId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Prijava");
                });

            modelBuilder.Entity("Earn_Learn.Models.Recenzija", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("datumRecenzije")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("idStudenta")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("idTutora")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("komentar")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ocjena")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Recenzija");
                });

            modelBuilder.Entity("Earn_Learn.Models.Termin", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<double>("cijena")
                        .HasColumnType("double");

                    b.Property<DateTime>("datumIVrijeme")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("idPredmeta")
                        .HasColumnType("int");

                    b.Property<string>("idStudenta")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("idTutora")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("qrKod")
                        .HasColumnType("longtext");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.Property<int>("tipInstrukcija")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Termin");
                });

            modelBuilder.Entity("Earn_Learn.Models.Transakcija", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("datumUplate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("idStudenta")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("idTutora")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("iznos")
                        .HasColumnType("double");

                    b.Property<int>("nacinPlacanja")
                        .HasColumnType("int");

                    b.Property<int>("statusPlacanja")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Transakcija");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Earn_Learn.Models.Korisnik", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Earn_Learn.Models.Korisnik", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Earn_Learn.Models.Korisnik", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Earn_Learn.Models.Korisnik", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
